/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Noman ali
 */
public class Login extends JFrame {

    /**
     * Creates new form Login
     */
       conjoin objbal;
       Connection objcon=null;
       Statement objstat=null;
       ResultSet objset=null;
       ResultSet objt=null;
       
    public Login() {
        super("Telephone connection system");
        initComponents();
        ImageIcon icon=new ImageIcon("src\\images\\e.png");
        this.setIconImage(icon.getImage());
        
        
          btnsign.requestFocus();
        
       
        
        screensize();
        look();
    }
    
      public final void screensize()
    {
        this.setSize(750, 400);
       Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       int w=this.getSize().width;
       int h=this.getSize().height;
       int x=(dim.width-w)/2;
       int y=(dim.height-h)/2;
       this.setLocation(x, y);
        
    }
      
       public final void look()
    {
      try{
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
         SwingUtilities.updateComponentTreeUI(this );
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, "program does not support window look and feel");
      }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btnexit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnsign = new javax.swing.JButton();
        maincombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 340));
        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);

        txtuser.setBackground(new java.awt.Color(230, 230, 230));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(102, 102, 102));
        txtuser.setText("User Name");
        txtuser.setToolTipText("Enter user name");
        txtuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtuserMouseExited(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });

        txtpass.setBackground(new java.awt.Color(230, 230, 230));
        txtpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(102, 102, 102));
        txtpass.setText("adminssss");
        txtpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpassMouseClicked(evt);
            }
        });
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassFocusLost(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exitbtn.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setDefaultCapable(false);
        btnexit.setFocusPainted(false);
        btnexit.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitbtnclick.png"))); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginname.png"))); // NOI18N
        jLabel3.setText("          ");

        btnsign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbtn.png"))); // NOI18N
        btnsign.setBorder(null);
        btnsign.setBorderPainted(false);
        btnsign.setContentAreaFilled(false);
        btnsign.setFocusPainted(false);
        btnsign.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnsign.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbtnclick.png"))); // NOI18N
        btnsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignActionPerformed(evt);
            }
        });

        maincombo.setBackground(new java.awt.Color(233, 233, 233));
        maincombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maincombo.setForeground(new java.awt.Color(102, 102, 102));
        maincombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "EMPLOYER" }));
        maincombo.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexit)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maincombo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maincombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnexit)
                    .addComponent(btnsign))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 130, 320, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainlogn.png.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 370, 240);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/equinor.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 10, 320, 90);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 440, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loginbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignActionPerformed
        
         objbal=new conjoin();
        if(txtuser.getText().equals("User Name"))
        {
                 ImageIcon icon = new ImageIcon("src\\images\\Administrator-icon.png");

            JOptionPane.showMessageDialog(null, "Enter User Name", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
              
        }
        else if(txtpass.getText().equals("adminssss"))
        {
            ImageIcon icon = new ImageIcon("src\\images\\App-password-icon.png");

            JOptionPane.showMessageDialog(null, "Enter password", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
               
        }
            
        else
        {
           try
           { 
               if(maincombo.getSelectedItem().equals("EMPLOYER"))
               {  
                objcon=objbal.sqlconnect();
                objset=objbal.resultquery("select Emp_username,Emp_name, Emp_pass , Emp_id from Emp_detail where Emp_username='"+txtuser.getText()+"' and Emp_pass='"+txtpass.getText()+"'");
                if(objset.next())
                {
                  ImageIcon icon = new ImageIcon("src\\images\\Apps-preferences-system-login-icon.png");

                      JOptionPane.showMessageDialog(null, "Login successful", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
                      emp_panel obj=new emp_panel();
                    
                      String ename=objset.getString("Emp_name");
                       functioncall.uname=(ename);
                       
                       
                       String id=objset.getString("Emp_id");
                       functioncall.id=(id);
                      obj.setVisible(true);
                   
                       this.dispose();
                       
                }
                
                else
                {
                     JOptionPane.showMessageDialog(null, "incorect login detail");
                     txtuser.setText("User Name");
                     txtpass.setText("adminssss");
                   
                }
               }
               
              else if(maincombo.getSelectedItem().equals("ADMIN"))
               {
               
                objt=objbal.resultquery("select Username,Admin_id , Name,Password from Administrator where Username='"+txtuser.getText()+"' and Password='"+txtpass.getText()+"'");
                if(objt.next())
                {
                  ImageIcon icon = new ImageIcon("src\\images\\Apps-preferences-system-login-icon.png");

                      JOptionPane.showMessageDialog(null, "Login successful", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
                       MainFrame obj=new MainFrame();
                       
                       
                       String ids=objt.getString(2);
                       functioncall.id=(ids);
                        String names=objt.getString(3);
                       functioncall.uname=(names);
                        obj.setVisible(true);
                   
                   
                        this.dispose();
               }
                else
                {
                     JOptionPane.showMessageDialog(null, "incorect login detail");
                     txtuser.setText("User Name");
                     txtpass.setText("adminssss");
                   
                }
           }
               else
               {
                 
               }
           }
             catch(Exception ex)
           {
               JOptionPane.showMessageDialog(null, ex);
           }
        }
    }//GEN-LAST:event_btnsignActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        ImageIcon icon=new ImageIcon("src\\images\\Close-2-icon.png");
       int z= JOptionPane.showConfirmDialog(null, "Do you want to Exit", "Confirm Message", JOptionPane.INFORMATION_MESSAGE, WIDTH, icon);
        if(z==0)
        {
               System.exit(z);
        }
        else
        {
                   
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        // TODO add your handling code here:
        if(txtuser.getText().equals("User Name"))
        {
            txtuser.setText("");
        }
        else
        {
           
        }
    }//GEN-LAST:event_txtuserMouseClicked

    private void txtuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseExited
       
    }//GEN-LAST:event_txtuserMouseExited

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
        if(txtuser.getText().equals(""))
        {
            txtuser.setText("User Name");
        }
        else
        {
           
        }
    }//GEN-LAST:event_txtuserFocusLost

    private void txtpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMouseClicked
        if(txtpass.getText().equals("adminssss"))
        {
            txtpass.setText("");
        }
        else
        {
           
        }
    }//GEN-LAST:event_txtpassMouseClicked

    private void txtpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusLost
         if(txtpass.getText().equals(""))
        {
            txtpass.setText("adminssss");
        }
        else
        {
           
        }
    }//GEN-LAST:event_txtpassFocusLost

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
           
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
       
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
       
       
       
     
    }//GEN-LAST:event_txtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox maincombo;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
