/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Noman ali
 */
public class Mobile_number_sale1 extends JInternalFrame{

    /**
     * Creates new form Mobile_number_sale
     */
     conjoin obj=new conjoin();
    Connection con;
    Statement sta;
    ResultSet rsta;
//    public String id;
//    public String name;
    public Mobile_number_sale1() {
        initComponents();
       
        empname.setText(functioncall.uname);
        empid.setText(functioncall.id);
        
        
          try {
               rsta=obj.resultquery("Select mobile_number from mobile_num where status='AVAILABLE'");
               combonumber.removeAllItems();
               combonumber.addItem("Select Here");
              
               
               while(rsta.next())
               {
                   combonumber.addItem(rsta.getString("mobile_number"));
               }
         } catch (Exception ex) {
             Logger.getLogger(Mobile_number_sale1.class.getName()).log(Level.SEVERE, null, ex);
         } 
          
           searchcombo.setEnabled(false);
           packsearch.setEnabled(false);
           searchbutton.setEnabled(false);
           packid.setEnabled(false);
           txtpackid.setEnabled(false);
           packprice.setEnabled(false); 
          
           Timer time=new Timer(60, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               //To change body of generated methods, choose Tools | Templates.
                
                 int Month,day,year;
        int second ,minute,hours,am;
        
        GregorianCalendar cln=new GregorianCalendar();
        
        day=cln.get(Calendar.DAY_OF_MONTH);
        Month=cln.get(Calendar.MONTH);
        year=cln.get(Calendar.YEAR);
        second=cln.get(Calendar.SECOND);
        minute=cln.get(Calendar.MINUTE);
        hours=cln.get(Calendar.HOUR);
        am=cln.get(Calendar.AM_PM);
        
        
        
           txtdate.setText(""+day+" / "+(Month+1)+" / "+year+"");
           if(am==0)
           {
             txttime.setText(" "+hours+" : "+minute+" : "+second+" AM");
           }
           else
           {
              txttime.setText(" "+hours+" : "+minute+" : "+second+" PM");
           }
        
 
     
            }
        });
             time.start();
             
    
        
    }
    
    
    
    private void remove()
    {
       cus_id.setText("");
       cus_name.setText("");
       combonumber.setSelectedItem("Select Here");
       cmbcity.setSelectedItem("Select City");
       cmbcountry.setSelectedItem("Select Country");
       
       txtpackid.setText("");
       packprice.setText("");
      
    }
   
    private void cussearch()
    {
         try {
             if(rsta.next())
             {
                cus_id.setText(rsta.getString(1));
                cus_name.setText(rsta.getString(2));
                 
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Record Not found");
                 cussearch.setText("");
                 cus_id.setText("");
                 cus_name.setText("");
             }
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
             
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cus_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        cussearch = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbcountry = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbcity = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        combonumber = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        typecon = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        packsearch = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        packid = new javax.swing.JLabel();
        txtpackid = new javax.swing.JTextField();
        packprice = new javax.swing.JTextField();
        searchcombo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(getBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mobile Number Sale");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e.png"))); // NOI18N
        setVisible(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Numbers-icon.png"))); // NOI18N
        jLabel1.setText("SALE MOBILE NUMBER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Employer Detail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employer ID :");

        empid.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("EMPLOYER NAME :");

        empname.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empid)
                    .addComponent(empname, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Customer Detail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(102, 102, 102)));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Zoom-icon (1).png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CUSTOMER ID :");

        cus_id.setEditable(false);
        cus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_idActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("CUSTOMER NAME :");

        cus_name.setEditable(false);

        try{
            cussearch.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("NIC :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cus_name)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cus_id, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cussearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cussearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cus_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Number Registeration", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(102, 102, 102)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("SELECT NUMBER");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("COUNTRY :");

        cmbcountry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbcountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Country", "Pakistan" }));
        cmbcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcountryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CITY :");

        cmbcity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbcity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select City", "" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DATE :");

        txtdate.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("TIME :");

        txttime.setEditable(false);

        combonumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combonumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Here" }));
        combonumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combonumberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combonumberMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combonumberMousePressed(evt);
            }
        });
        combonumber.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combonumberPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combonumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combonumberActionPerformed(evt);
            }
        });
        combonumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combonumberFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbcountry, 0, 134, Short.MAX_VALUE)
                    .addComponent(cmbcity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdate)
                    .addComponent(txttime)
                    .addComponent(combonumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combonumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Connection Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(102, 102, 102)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("TYPE OF CONNECTION :");

        typecon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        typecon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Here", "POSTPAID", "PREPAID" }));
        typecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(49, 49, 49)
                .addComponent(typecon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(typecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Package info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(102, 102, 102)));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Zoom-icon (1).png"))); // NOI18N
        searchbutton.setText("SEARCH");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        packid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        packid.setText("PACKAGE Name :");

        txtpackid.setEditable(false);

        packprice.setEditable(false);

        searchcombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchcombo.setText("PACKAGE ID :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchcombo)
                    .addComponent(packid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtpackid, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(packprice, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(packsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbutton)))
                .addGap(60, 60, 60))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbutton)
                    .addComponent(searchcombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packid)
                    .addComponent(txtpackid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-add-icon.png"))); // NOI18N
        jButton3.setText("REGISTRATION ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close-2-icon.png"))); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 443, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             if(cussearch.getText().equals("     -       - "))  
             {
                 
                JOptionPane.showMessageDialog(null, "Enter Customer NIC");
             }
             else
             {
                 try{
            

                rsta=obj.resultquery("select cus_id,cus_name from customer where cus_nic= '"+cussearch.getText()+"'");  
                this.cussearch();
             
                   
                 

            }
            catch(Exception ex)
            {
              JOptionPane.showMessageDialog(null, "ex");
             
            }
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcountryActionPerformed
          String Count = cmbcountry.getSelectedItem().toString();        
          cmbcity.removeAllItems();
        
        if(Count.equals("Pakistan"))
        {
            cmbcity.addItem("Select City");
            cmbcity.addItem("Karachi");
            cmbcity.addItem("Lahore");
            cmbcity.addItem("Islamabad");
            cmbcity.addItem("Multan");
            cmbcity.addItem("Rawalpindi");
            cmbcity.addItem("Peshawar");
            cmbcity.addItem("Queta");
            cmbcity.addItem("Sahiwal");
        }
        else
        {
          cmbcity.addItem("Select City");
        }
        
          
      
    }//GEN-LAST:event_cmbcountryActionPerformed

    private void combonumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combonumberFocusGained
               try {
               rsta=obj.resultquery("Select mobile_number from mobile_num where status='AVAILABLE'");
               combonumber.removeAllItems();
               combonumber.addItem("Select Here");
              
               
               while(rsta.next())
               {
                   combonumber.addItem(rsta.getString("mobile_number"));
               }
         } catch (Exception ex) {
             Logger.getLogger(Mobile_number_sale1.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_combonumberFocusGained

    private void combonumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combonumberMouseClicked
                            
    }//GEN-LAST:event_combonumberMouseClicked

    private void combonumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combonumberActionPerformed
             
    }//GEN-LAST:event_combonumberActionPerformed
  
      public void packsearchs()
    {
         try {
             if(rsta.next())
             {
                 txtpackid.setText(rsta.getString("Pakage_name"));
                 packprice.setText(rsta.getString("pakage_Price")+  "PKR");
                
                 
             }
             else
             {
                JOptionPane.showMessageDialog(null, "Record Not Found");
                packsearch.setText("");
                txtpackid.setText("");
                packprice.setText("");
             }
         }
         catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
             
            
         }
    }
    
    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
            if(packsearch.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "Enter Package ID");
        }
        else
        {
           try
           {

                  
                   rsta=obj.resultquery("select Pakage_name,pakage_Price from Mobile_pakage where  pack_id= '"+packsearch.getText()+"' AND Status='Available'"); 
                   this. packsearchs();

                   
           }
           
           catch(Exception ex)
           {
             JOptionPane.showMessageDialog(null, ex);
           }
        }  
        
        
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try {
                     int eid=Integer.parseInt(empid.getText());
                     String ename=empname.getText();
                     String cid=cus_id.getText();
                     String cname=cus_name.getText();
                     String num=combonumber.getSelectedItem().toString();
                     String cntry=cmbcountry.getSelectedItem().toString();
                     String cit=cmbcity.getSelectedItem().toString();
                     String date=txtdate.getText();
                     String time=txttime.getText();
                     String cons=typecon.getSelectedItem().toString();
                     String pname=txtpackid.getText();
                  
                  if(cus_id.getText().equals(""))
                  {
                      JOptionPane.showMessageDialog(null, "Enter Cutomer ID");
                  }
                  else if(cus_name.getText().equals(""))
                  {
                   JOptionPane.showMessageDialog(null, "Enter Customer Name");
                  }
                  else if(combonumber.getSelectedItem().equals("Select Here"))
                  {
                    JOptionPane.showMessageDialog(null, "Select Mobile Number");
                  }
                  else if(cmbcountry.getSelectedItem().equals("Select Country"))
                  {
                    JOptionPane.showMessageDialog(null, "Select Country");
                  }
                  else if(cmbcity.getSelectedItem().equals("Select City"))
                  {
                    JOptionPane.showMessageDialog(null, "Select City");
                  }
                  else if(typecon.getSelectedItem().equals("Select Here"))
                  {
                      JOptionPane.showMessageDialog(null, "Select Type Of Connection");
                  }
                  else if(typecon.getSelectedItem().equals("POSTPAID"))
                  {
                      if(txtpackid.getText().equals(""))
                      {
                          JOptionPane.showMessageDialog(null, "Enter Package Name");
                                 
                      }
                      else
                      {
                          
                         con=obj.sqlconnect();
                   sta=con.createStatement();
                  int result= sta.executeUpdate("insert into Mobile_Registration values("+eid+",'"+ename+"','"+cid+"','"+cname+"','"+num+"','"+cntry+"','"+cit+"','"+date+"','"+time+"','MOBILE','"+cons+"','"+pname+"')");
                  if(result>0)
                  {
                     JOptionPane.showMessageDialog(null, "Record SuccessFully Save");
                     sta.executeUpdate("update mobile_num set status='NOT AVAILABLE' where mobile_number='"+num+"'");
                     this.remove();
                  }
                  else
                  {
                       JOptionPane.showMessageDialog(null, "Record Not Save");
                  }
                      }
                  }
                  
                  else if(typecon.getSelectedItem().equals("PREPAID"))
                  {
                     
                        con=obj.sqlconnect();
                   sta=con.createStatement();
                  int result= sta.executeUpdate("insert into Mobile_Registration values("+eid+",'"+ename+"','"+cid+"','"+cname+"','"+num+"','"+cntry+"','"+cit+"','"+date+"','"+time+"','MOBILE','"+cons+"','"+pname+"')");
                  if(result>0)
                  {
                     JOptionPane.showMessageDialog(null, "Record SuccessFully Save");
                     sta.executeUpdate("update mobile_num set status='NOT AVAILABLE' where mobile_number='"+num+"'");
                     this.remove();
                  }
                  else
                  {
                       JOptionPane.showMessageDialog(null, "Record Not Save");
                  }
                      
                      
                  }
                      
                  else
                  {
                  
                   
                   
                  JOptionPane.showMessageDialog(null, "code error");
                  
                
                }
                   
                     
                     
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void typeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeconActionPerformed
       if(typecon.getSelectedItem().equals("POSTPAID"))  
       {
           searchcombo.setEnabled(true);
           packsearch.setEnabled(true);
           searchbutton.setEnabled(true);
           packid.setEnabled(true);
           txtpackid.setEnabled(true);
           packprice.setEnabled(true);        
       }
       else if(typecon.getSelectedItem().equals("PREPAID"))
       {
           searchcombo.setEnabled(false);
           packsearch.setEnabled(false);
           searchbutton.setEnabled(false);
           packid.setEnabled(false);
           txtpackid.setEnabled(false);
           packprice.setEnabled(false); 
           packsearch.setText("");
           txtpackid.setText("");
           packprice.setText("");
       }
       else
       {
       
       }
        
    }//GEN-LAST:event_typeconActionPerformed

    private void combonumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combonumberMouseEntered
                  
        
    }//GEN-LAST:event_combonumberMouseEntered

    private void combonumberPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combonumberPopupMenuWillBecomeInvisible
          
    }//GEN-LAST:event_combonumberPopupMenuWillBecomeInvisible

    private void combonumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combonumberMousePressed
    
    }//GEN-LAST:event_combonumberMousePressed

    private void cus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_idActionPerformed
        
    }//GEN-LAST:event_cus_idActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbcity;
    private javax.swing.JComboBox cmbcountry;
    private javax.swing.JComboBox combonumber;
    private javax.swing.JTextField cus_id;
    private javax.swing.JTextField cus_name;
    private javax.swing.JFormattedTextField cussearch;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel packid;
    private javax.swing.JTextField packprice;
    private javax.swing.JTextField packsearch;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel searchcombo;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtpackid;
    private javax.swing.JTextField txttime;
    private javax.swing.JComboBox typecon;
    // End of variables declaration//GEN-END:variables

    void account(String string, String string0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
